/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * AD24xx register map
 *
 * Copyright (c) 2023 Alvin Šipraga <alsi@bang-olufsen.dk>
 */

#ifndef _AD24XX_H
#define _AD24XX_H

enum ad24xx_regs {
	A2B_CHIP = 0x00,	/* I2C Chip Address Register (sub only) */
	A2B_NODEADR = 0x01,	/* Node Address Register (main only) */
	A2B_VENDOR = 0x02,	/* Vendor ID Register */
	A2B_PRODUCT = 0x03,	/* Product ID Register */
	A2B_VERSION = 0x04,	/* Version ID Register */
	A2B_CAPABILITY = 0x05,	/* Capability ID Register */
	A2B_SWCTL = 0x09,	/* Switch Control Register */
	A2B_BCDNSLOTS = 0x0A,	/* Broadcast Downstream Slots Register (sub only) */
	A2B_LDNSLOTS = 0x0B,	/* Local Downstream Slots Register (sub only) */
	A2B_LUPSLOTS = 0x0C,	/* Local Upstream Slots Register (sub only) */
	A2B_DNSLOTS = 0x0D,	/* Downstream Slots Register */
	A2B_UPSLOTS = 0x0E,	/* Upstream Slots Register */
	A2B_RESPCYCS = 0x0F,	/* Response Cycles Register */
	A2B_SLOTFMT = 0x10,	/* Slot Format Register (main only, Auto-Broadcast) */
	A2B_DATCTL = 0x11,	/* Data Control Register (main only, Auto-Broadcast) */
	A2B_CONTROL = 0x12,	/* Control Register */
	A2B_DISCVRY = 0x13,	/* Discovery Register (main only) */
	A2B_SWSTAT = 0x14,	/* Switch Status Register */
	A2B_INTSTAT = 0x15,	/* Interrupt Status Register */
	A2B_INTSRC = 0x16,	/* Interrupt Source Register (main only) */
	A2B_INTTYPE = 0x17,	/* Interrupt Type Register (main only) */
	A2B_INTPND0 = 0x18,	/* Interrupt Pending 0 Register */
	A2B_INTPND1 = 0x19,	/* Interrupt Pending 1 Register */
	A2B_INTPND2 = 0x1A,	/* Interrupt Pending 2 Register (main only) */
	A2B_INTMSK0 = 0x1B,	/* Interrupt Mask 0 Register */
	A2B_INTMSK1 = 0x1C,	/* Interrupt Mask 1 Register */
	A2B_INTMSK2 = 0x1D,	/* Interrupt Mask 2 Register (main only) */
	A2B_BECCTL = 0x1E,	/* Bit Error Count Control Register */
	A2B_BECNT = 0x1F,	/* Bit Error Count Register */
	A2B_TESTMODE = 0x20,	/* Testmode Register */
	A2B_ERRCNT0 = 0x21,	/* PRBS Error Count Byte 0 Register */
	A2B_ERRCNT1 = 0x22,	/* PRBS Error Count Byte 1 Register */
	A2B_ERRCNT2 = 0x23,	/* PRBS Error Count Byte 2 Register */
	A2B_ERRCNT3 = 0x24,	/* PRBS Error Count Byte 3 Register */
	A2B_NODE = 0x29,	/* Node Register */
	A2B_DISCSTAT = 0x2B,	/* Discovery Status Register (main only) */
	A2B_TXACTL = 0x2E,	/* LVDSA TX Control Register */
	A2B_TXBCTL = 0x30,	/* LVDSB TX Control Register */
	A2B_LINTTYPE = 0x3E,	/* Local Interrupt Type (sub only) */
	A2B_I2CCFG = 0x3F,	/* I2C Configuration Register */
	A2B_PLLCTL = 0x40,	/* PLL Control Register */
	A2B_I2SGCFG = 0x41,	/* I2S Global Configuration Register */
	A2B_I2SCFG = 0x42,	/* I2S Configuration Register */
	A2B_I2SRATE = 0x43,	/* I2S Rate Register (sub only) */
	A2B_I2STXOFFSET = 0x44,	/* I2S Transmit Data Offset Register (main only) */
	A2B_I2SRXOFFSET = 0x45,	/* I2S Receive Data Offset Register (main only) */
	A2B_SYNCOFFSET = 0x46,	/* SYNC Offset Register (sub only) */
	A2B_PDMCTL = 0x47,	/* PDM Control Register */
	A2B_ERRMGMT = 0x48,	/* Error Management Register */
	A2B_GPIODAT = 0x4A,	/* GPIO Output Data Register */
	A2B_GPIODATSET = 0x4B,	/* GPIO Output Data Set Register */
	A2B_GPIODATCLR = 0x4C,	/* GPIO Output Data Clear Register */
	A2B_GPIOOEN = 0x4D,	/* GPIO Output Enable Register */
	A2B_GPIOIEN = 0x4E,	/* GPIO Input Enable Register */
	A2B_GPIOIN = 0x4F,	/* GPIO Input Value Register */
	A2B_PINTEN = 0x50,	/* Pin Interrupt Enable Register */
	A2B_PINTINV = 0x51,	/* Pin Interrupt Invert Register */
	A2B_PINCFG = 0x52,	/* Pin Configuration Register */
	A2B_I2STEST = 0x53,	/* I2S Test Register */
	A2B_RAISE = 0x54,	/* Raise Interrupt Register */
	A2B_GENERR = 0x55,	/* Generate Bus Error */
	A2B_I2SRRATE = 0x56,	/* I2S Reduced Rate Register (main only, Auto-Broadcast) */
	A2B_I2SRRCTL = 0x57,	/* I2S Reduced Rate Control Register */
	A2B_I2SRRSOFFS = 0x58,	/* I2S Reduced Rate SYNC Offset Register (sub only) */
	A2B_CLK1CFG = 0x59,	/* CLKOUT1 Configuration Register */
	A2B_CLK2CFG = 0x5A,	/* CLKOUT2 Configuration Register */
	A2B_BMMCFG = 0x5B,	/* Bus Monitor Mode Configuration Register */
	A2B_SUSCFG = 0x5C,	/* Sustain Configuration Register (sub only) */
	A2B_PDMCTL2 = 0x5D,	/* PDM Control 2 Register */
	A2B_UPMASK0 = 0x60,	/* Upstream Data RX Mask 0 Register (sub only) */
	A2B_UPMASK1 = 0x61,	/* Upstream Data RX Mask 1 Register (sub only) */
	A2B_UPMASK2 = 0x62,	/* Upstream Data RX Mask 2 Register (sub only) */
	A2B_UPMASK3 = 0x63,	/* Upstream Data RX Mask 3 Register (sub only) */
	A2B_UPOFFSET = 0x64,	/* Local Upstream Channel Offset Register (sub only) */
	A2B_DNMASK0 = 0x65,	/* Downstream Data RX Mask 0 Register (sub only) */
	A2B_DNMASK1 = 0x66,	/* Downstream Data RX Mask 1 Register (sub only) */
	A2B_DNMASK2 = 0x67,	/* Downstream Data RX Mask 2 Register (sub only) */
	A2B_DNMASK3 = 0x68,	/* Downstream Data RX Mask 3 Register (sub only) */
	A2B_DNOFFSET = 0x69,	/* Local Downstream Channel Offset Register (sub only) */
	A2B_CHIPID0 = 0x6A,	/* Chip ID Register 0 */
	A2B_CHIPID1 = 0x6B,	/* Chip ID Register 1 */
	A2B_CHIPID2 = 0x6C,	/* Chip ID Register 2 */
	A2B_CHIPID3 = 0x6D,	/* Chip ID Register 3 */
	A2B_CHIPID4 = 0x6E,	/* Chip ID Register 4 */
	A2B_CHIPID5 = 0x6F,	/* Chip ID Register 5 */
	A2B_GPIODEN = 0x80,	/* GPIO Over Distance Enable Register */
	A2B_GPIOD0MSK = 0x81,	/* GPIO Over Distance Mask 0 Register */
	A2B_GPIOD1MSK = 0x82,	/* GPIO Over Distance Mask 1 Register */
	A2B_GPIOD2MSK = 0x83,	/* GPIO Over Distance Mask 2 Register */
	A2B_GPIOD3MSK = 0x84,	/* GPIO Over Distance Mask 3 Register */
	A2B_GPIOD4MSK = 0x85,	/* GPIO Over Distance Mask 4 Register */
	A2B_GPIOD5MSK = 0x86,	/* GPIO Over Distance Mask 5 Register */
	A2B_GPIOD6MSK = 0x87,	/* GPIO Over Distance Mask 6 Register */
	A2B_GPIOD7MSK = 0x88,	/* GPIO Over Distance Mask 7 Register */
	A2B_GPIODDAT = 0x89,	/* GPIO Over Distance Data Register */
	A2B_GPIODINV = 0x8A,	/* GPIO Over Distance Invert Register */
	A2B_MBOX0CTL = 0x90,	/* Mailbox 0 Control Register (sub only) */
	A2B_MBOX0STAT = 0x91,	/* Mailbox 0 Status Register (sub only) */
	A2B_MBOX0B0 = 0x92,	/* Mailbox 0 Byte 0 Register (sub only) */
	A2B_MBOX0B1 = 0x93,	/* Mailbox 0 Byte 1 Register (sub only) */
	A2B_MBOX0B2 = 0x94,	/* Mailbox 0 Byte 2 Register (sub only) */
	A2B_MBOX0B3 = 0x95,	/* Mailbox 0 Byte 3 Register (sub only) */
	A2B_MBOX1CTL = 0x96,	/* Mailbox 1 Control Register (sub only) */
	A2B_MBOX1STAT = 0x97,	/* Mailbox 1 Status Register (sub only) */
	A2B_MBOX1B0 = 0x98,	/* Mailbox 1 Byte 0 Register (sub only) */
	A2B_MBOX1B1 = 0x99,	/* Mailbox 1 Byte 1 Register (sub only) */
	A2B_MBOX1B2 = 0x9A,	/* Mailbox 1 Byte 2 Register (sub only) */
	A2B_MBOX1B3 = 0x9B,	/* Mailbox 1 Byte 3 Register (sub only) */
};

// TODO: It's so easy to mix these up with the _MASK versions that I commented
// it out for now. But it might come in handy later... #if 0 it...
#if 0
enum ad24xx_regfields {
	A2B_CHIP_CHIPADR,
	A2B_NODEADR_NODE,
	A2B_NODEADR_PERI,
	A2B_NODEADR_BRCST,
	A2B_VENDOR_VENDOR,
	A2B_PRODUCT_PRODUCT,
	A2B_VERSION_VERSION,
	A2B_CAPABILITY_I2CAVAIL,
	A2B_SWCTL_ENSW,
	A2B_SWCTL_DIAGMODE,
	A2B_SWCTL_MODE,
	A2B_SWCTL_DISNXT,
	A2B_BCDNSLOTS_BCDNSLOTS,
	A2B_LDNSLOTS_LDNSLOTS,
	A2B_LDNSLOTS_DNMASKEN,
	A2B_LUPSLOTS_LUPSLOTS,
	A2B_DNSLOTS_DNSLOTS,
	A2B_UPSLOTS_UPSLOTS,
	A2B_RESPCYCS_RESPCYCS,
	A2B_SLOTFMT_DNSIZE,
	A2B_SLOTFMT_DNFP,
	A2B_SLOTFMT_UPSIZE,
	A2B_SLOTFMT_UPFMT,
	A2B_DATCTL_DNS,
	A2B_DATCTL_UPS,
	A2B_DATCTL_ENDSNIFF,
	A2B_DATCTL_STANDBY,
	A2B_CONTROL_NEWSTRCT,
	A2B_CONTROL_ENDDSC,
	A2B_CONTROL_SOFTRST,
	A2B_CONTROL_SWBYP,
	A2B_CONTROL_XCVRBINV,
	A2B_CONTROL_MSTR,
	A2B_DISCVRY_DRESPCYC,
	A2B_SWSTAT_FIN,
	A2B_SWSTAT_FAULT,
	A2B_SWSTAT_FAULT_CODE,
	A2B_SWSTAT_FAULT_NLOC,
	A2B_INTSTAT_IRQ,
	A2B_INTSRC_INODE,
	A2B_INTSRC_SLVINT,
	A2B_INTSRC_MSTINT,
	A2B_INTTYPE_TYPE,
	A2B_INTPND0_HDCNTERR,
	A2B_INTPND0_DDERR,
	A2B_INTPND0_CRCERR,
	A2B_INTPND0_DPERR,
	A2B_INTPND0_PWRERR,
	A2B_INTPND0_BECOVF,
	A2B_INTPND0_SRFERR,
	A2B_INTPND0_SRFCRCERR,
	A2B_INTPND1_IO0PND,
	A2B_INTPND1_IO1PND,
	A2B_INTPND1_IO2PND,
	A2B_INTPND1_IO3PND,
	A2B_INTPND1_IO4PND,
	A2B_INTPND1_IO5PND,
	A2B_INTPND1_IO6PND,
	A2B_INTPND1_IO7PND,
	A2B_INTPND2_DSCDONE,
	A2B_INTPND2_I2CERR,
	A2B_INTPND2_ICRCERR,
	A2B_INTPND2_SLVIRQ,
	A2B_INTMSK0_HDEIEN,
	A2B_INTMSK0_DDEIEN,
	A2B_INTMSK0_CRCEIEN,
	A2B_INTMSK0_DPEIEN,
	A2B_INTMSK0_PWREIEN,
	A2B_INTMSK0_BECIEN,
	A2B_INTMSK0_SRFEIEN,
	A2B_INTMSK0_SRFCRCEIEN,
	A2B_INTMSK1_IO0IRQEN,
	A2B_INTMSK1_IO1IRQEN,
	A2B_INTMSK1_IO2IRQEN,
	A2B_INTMSK1_IO3IRQEN,
	A2B_INTMSK1_IO4IRQEN,
	A2B_INTMSK1_IO5IRQEN,
	A2B_INTMSK1_IO6IRQEN,
	A2B_INTMSK1_IO7IRQEN,
	A2B_INTMSK2_DSCDIEN,
	A2B_INTMSK2_I2CEIEN,
	A2B_INTMSK2_ICRCEIEN,
	A2B_INTMSK2_SLVIRQEN,
	A2B_BECCTL_ENHDCNT,
	A2B_BECCTL_ENDD,
	A2B_BECCTL_ENCRC,
	A2B_BECCTL_ENDP,
	A2B_BECCTL_ENICRC,
	A2B_BECCTL_THRESHLD,
	A2B_BECNT_BECNT,
	A2B_TESTMODE_PRBSUP,
	A2B_TESTMODE_PRBSDN,
	A2B_TESTMODE_PRBSN2N,
	A2B_TESTMODE_RXDPTH,
	A2B_ERRCNT0_ERRCNT,
	A2B_ERRCNT1_ERRCNT,
	A2B_ERRCNT2_ERRCNT,
	A2B_ERRCNT3_ERRCNT,
	A2B_NODE_NUMBER,
	A2B_NODE_DISCVD,
	A2B_NODE_NLAST,
	A2B_NODE_LAST,
	A2B_DISCSTAT_DNODE,
	A2B_DISCSTAT_DSCACT,
	A2B_TXACTL_TXALEVEL,
	A2B_TXACTL_TXAOVREN,
	A2B_TXBCTL_TXBLEVEL,
	A2B_TXBCTL_TXBOVREN,
	A2B_LINTTYPE_LTYPE,
	A2B_I2CCFG_DATARATE,
	A2B_I2CCFG_EACK,
	A2B_I2CCFG_FRAMERATE,
	A2B_PLLCTL_SSFREQ,
	A2B_PLLCTL_SSDEPTH,
	A2B_PLLCTL_SSMODE,
	A2B_I2SGCFG_TDMMODE,
	A2B_I2SGCFG_RXONDTX1,
	A2B_I2SGCFG_TDMSS,
	A2B_I2SGCFG_ALT,
	A2B_I2SGCFG_EARLY,
	A2B_I2SGCFG_INV,
	A2B_I2SCFG_TX0EN,
	A2B_I2SCFG_TX1EN,
	A2B_I2SCFG_TX2PINTL,
	A2B_I2SCFG_TXBCLKINV,
	A2B_I2SCFG_RX0EN,
	A2B_I2SCFG_RX1EN,
	A2B_I2SCFG_RX2PINTL,
	A2B_I2SCFG_RXBCLKINV,
	A2B_I2SRATE_I2SRATE,
	A2B_I2SRATE_BCLKRATE,
	A2B_I2SRATE_FRAMES,
	A2B_I2SRATE_REDUCE,
	A2B_I2SRATE_SHARE,
	A2B_I2STXOFFSET_TXOFFSET,
	A2B_I2STXOFFSET_TSAFTER,
	A2B_I2STXOFFSET_TSBEFORE,
	A2B_I2SRXOFFSET_RXOFFSET,
	A2B_SYNCOFFSET_SYNCOFFSET,
	A2B_PDMCTL_PDM0EN,
	A2B_PDMCTL_PDM0SLOTS,
	A2B_PDMCTL_PDM1EN,
	A2B_PDMCTL_PDM1SLOTS,
	A2B_PDMCTL_HPFEN,
	A2B_PDMCTL_PDMRATE,
	A2B_ERRMGMT_ERRLSB,
	A2B_ERRMGMT_ERRSIG,
	A2B_ERRMGMT_ERRSLOT,
	A2B_GPIODAT_IO0DAT,
	A2B_GPIODAT_IO1DAT,
	A2B_GPIODAT_IO2DAT,
	A2B_GPIODAT_IO3DAT,
	A2B_GPIODAT_IO4DAT,
	A2B_GPIODAT_IO5DAT,
	A2B_GPIODAT_IO6DAT,
	A2B_GPIODAT_IO7DAT,
	A2B_GPIODATSET_IO0DSET,
	A2B_GPIODATSET_IO1DSET,
	A2B_GPIODATSET_IO2DSET,
	A2B_GPIODATSET_IO3DSET,
	A2B_GPIODATSET_IO4DSET,
	A2B_GPIODATSET_IO5DSET,
	A2B_GPIODATSET_IO6DSET,
	A2B_GPIODATSET_IO7DSET,
	A2B_GPIODATCLR_IO0DCLR,
	A2B_GPIODATCLR_IO1DCLR,
	A2B_GPIODATCLR_IO2DCLR,
	A2B_GPIODATCLR_IO3DCLR,
	A2B_GPIODATCLR_IO4DCLR,
	A2B_GPIODATCLR_IO5DCLR,
	A2B_GPIODATCLR_IO6DCLR,
	A2B_GPIODATCLR_IO7DCLR,
	A2B_GPIOOEN_IO0OEN,
	A2B_GPIOOEN_IO1OEN,
	A2B_GPIOOEN_IO2OEN,
	A2B_GPIOOEN_IO3OEN,
	A2B_GPIOOEN_IO4OEN,
	A2B_GPIOOEN_IO5OEN,
	A2B_GPIOOEN_IO6OEN,
	A2B_GPIOOEN_IO7OEN,
	A2B_GPIOIEN_IO0IEN,
	A2B_GPIOIEN_IO1IEN,
	A2B_GPIOIEN_IO2IEN,
	A2B_GPIOIEN_IO3IEN,
	A2B_GPIOIEN_IO4IEN,
	A2B_GPIOIEN_IO5IEN,
	A2B_GPIOIEN_IO6IEN,
	A2B_GPIOIEN_IO7IEN,
	A2B_GPIOIN_IO0IN,
	A2B_GPIOIN_IO1IN,
	A2B_GPIOIN_IO2IN,
	A2B_GPIOIN_IO3IN,
	A2B_GPIOIN_IO4IN,
	A2B_GPIOIN_IO5IN,
	A2B_GPIOIN_IO6IN,
	A2B_GPIOIN_IO7IN,
	A2B_PINTEN_IO0IE,
	A2B_PINTEN_IO1IE,
	A2B_PINTEN_IO2IE,
	A2B_PINTEN_IO3IE,
	A2B_PINTEN_IO4IE,
	A2B_PINTEN_IO5IE,
	A2B_PINTEN_IO6IE,
	A2B_PINTEN_IO7IE,
	A2B_PINTINV_IO0INV,
	A2B_PINTINV_IO1INV,
	A2B_PINTINV_IO2INV,
	A2B_PINTINV_IO3INV,
	A2B_PINTINV_IO4INV,
	A2B_PINTINV_IO5INV,
	A2B_PINTINV_IO6INV,
	A2B_PINTINV_IO7INV,
	A2B_PINCFG_DRVSTR,
	A2B_PINCFG_IRQINV,
	A2B_PINCFG_IRQTS,
	A2B_I2STEST_PATTRN2TX,
	A2B_I2STEST_LOOPBK2TX,
	A2B_I2STEST_RX2LOOPBK,
	A2B_I2STEST_SELRX1,
	A2B_I2STEST_BUSLOOPBK,
	A2B_RAISE_RAISE,
	A2B_GENERR_GENHCERR,
	A2B_GENERR_GENDDERR,
	A2B_GENERR_GENCRCERR,
	A2B_GENERR_GENDPERR,
	A2B_GENERR_GENICRCERR,
	A2B_I2SRRATE_RRDIV,
	A2B_I2SRRATE_RBUS,
	A2B_I2SRRCTL_ENVLSB,
	A2B_I2SRRCTL_ENXBIT,
	A2B_I2SRRCTL_ENSTRB,
	A2B_I2SRRCTL_STRBDIR,
	A2B_I2SRRSOFFS_RRSOFFSET,
	A2B_CLK1CFG_CLK1DIV,
	A2B_CLK1CFG_CLK1PDIV,
	A2B_CLK1CFG_CLK1INV,
	A2B_CLK1CFG_CLK1EN,
	A2B_CLK2CFG_CLK1DIV,
	A2B_CLK2CFG_CLK1PDIV,
	A2B_CLK2CFG_CLK1INV,
	A2B_CLK2CFG_CLK1EN,
	A2B_BMMCFG_BMMEN,
	A2B_BMMCFG_BMMRXEN,
	A2B_BMMCFG_BMMNDSC,
	A2B_SUSCFG_SUSSEL,
	A2B_SUSCFG_SUSOE,
	A2B_SUSCFG_SUSDIS,
	A2B_PDMCTL2_PDMDEST,
	A2B_PDMCTL2_PDM0FFRST,
	A2B_PDMCTL2_PDM1FFRST,
	A2B_PDMCTL2_PDMALTCLK,
	A2B_PDMCTL2_PDMINVCLK,
	A2B_UPMASK0_RXUPSLOT00,
	A2B_UPMASK0_RXUPSLOT01,
	A2B_UPMASK0_RXUPSLOT02,
	A2B_UPMASK0_RXUPSLOT03,
	A2B_UPMASK0_RXUPSLOT04,
	A2B_UPMASK0_RXUPSLOT05,
	A2B_UPMASK0_RXUPSLOT06,
	A2B_UPMASK0_RXUPSLOT07,
	A2B_UPMASK1_RXUPSLOT08,
	A2B_UPMASK1_RXUPSLOT09,
	A2B_UPMASK1_RXUPSLOT10,
	A2B_UPMASK1_RXUPSLOT11,
	A2B_UPMASK1_RXUPSLOT12,
	A2B_UPMASK1_RXUPSLOT13,
	A2B_UPMASK1_RXUPSLOT14,
	A2B_UPMASK1_RXUPSLOT15,
	A2B_UPMASK2_RXUPSLOT16,
	A2B_UPMASK2_RXUPSLOT17,
	A2B_UPMASK2_RXUPSLOT18,
	A2B_UPMASK2_RXUPSLOT19,
	A2B_UPMASK2_RXUPSLOT20,
	A2B_UPMASK2_RXUPSLOT21,
	A2B_UPMASK2_RXUPSLOT22,
	A2B_UPMASK2_RXUPSLOT23,
	A2B_UPMASK3_RXUPSLOT24,
	A2B_UPMASK3_RXUPSLOT25,
	A2B_UPMASK3_RXUPSLOT26,
	A2B_UPMASK3_RXUPSLOT27,
	A2B_UPMASK3_RXUPSLOT28,
	A2B_UPMASK3_RXUPSLOT29,
	A2B_UPMASK3_RXUPSLOT30,
	A2B_UPMASK3_RXUPSLOT31,
	A2B_UPOFFSET_UPOFFSET,
	A2B_DNMASK0_RXDNSLOT00,
	A2B_DNMASK0_RXDNSLOT01,
	A2B_DNMASK0_RXDNSLOT02,
	A2B_DNMASK0_RXDNSLOT03,
	A2B_DNMASK0_RXDNSLOT04,
	A2B_DNMASK0_RXDNSLOT05,
	A2B_DNMASK0_RXDNSLOT06,
	A2B_DNMASK0_RXDNSLOT07,
	A2B_DNMASK1_RXDNSLOT08,
	A2B_DNMASK1_RXDNSLOT09,
	A2B_DNMASK1_RXDNSLOT10,
	A2B_DNMASK1_RXDNSLOT11,
	A2B_DNMASK1_RXDNSLOT12,
	A2B_DNMASK1_RXDNSLOT13,
	A2B_DNMASK1_RXDNSLOT14,
	A2B_DNMASK1_RXDNSLOT15,
	A2B_DNMASK2_RXDNSLOT16,
	A2B_DNMASK2_RXDNSLOT17,
	A2B_DNMASK2_RXDNSLOT18,
	A2B_DNMASK2_RXDNSLOT19,
	A2B_DNMASK2_RXDNSLOT20,
	A2B_DNMASK2_RXDNSLOT21,
	A2B_DNMASK2_RXDNSLOT22,
	A2B_DNMASK2_RXDNSLOT23,
	A2B_DNMASK3_RXDNSLOT24,
	A2B_DNMASK3_RXDNSLOT25,
	A2B_DNMASK3_RXDNSLOT26,
	A2B_DNMASK3_RXDNSLOT27,
	A2B_DNMASK3_RXDNSLOT28,
	A2B_DNMASK3_RXDNSLOT29,
	A2B_DNMASK3_RXDNSLOT30,
	A2B_DNMASK3_RXDNSLOT31,
	A2B_DNOFFSET_DNOFFSET,
	A2B_CHIPID0_CHIPID,
	A2B_CHIPID1_CHIPID,
	A2B_CHIPID2_CHIPID,
	A2B_CHIPID3_CHIPID,
	A2B_CHIPID4_CHIPID,
	A2B_CHIPID5_CHIPID,
	A2B_GPIODEN_IOD0EN,
	A2B_GPIODEN_IOD1EN,
	A2B_GPIODEN_IOD2EN,
	A2B_GPIODEN_IOD3EN,
	A2B_GPIODEN_IOD4EN,
	A2B_GPIODEN_IOD5EN,
	A2B_GPIODEN_IOD6EN,
	A2B_GPIODEN_IOD7EN,
	A2B_GPIOD0MSK_IOD0MSK,
	A2B_GPIOD1MSK_IOD1MSK,
	A2B_GPIOD2MSK_IOD2MSK,
	A2B_GPIOD3MSK_IOD3MSK,
	A2B_GPIOD4MSK_IOD4MSK,
	A2B_GPIOD5MSK_IOD5MSK,
	A2B_GPIOD6MSK_IOD6MSK,
	A2B_GPIOD7MSK_IOD7MSK,
	A2B_GPIODDAT_IOD0DAT,
	A2B_GPIODDAT_IOD1DAT,
	A2B_GPIODDAT_IOD2DAT,
	A2B_GPIODDAT_IOD3DAT,
	A2B_GPIODDAT_IOD4DAT,
	A2B_GPIODDAT_IOD5DAT,
	A2B_GPIODDAT_IOD6DAT,
	A2B_GPIODDAT_IOD7DAT,
	A2B_GPIODINV_IOD0INV,
	A2B_GPIODINV_IOD1INV,
	A2B_GPIODINV_IOD2INV,
	A2B_GPIODINV_IOD3INV,
	A2B_GPIODINV_IOD4INV,
	A2B_GPIODINV_IOD5INV,
	A2B_GPIODINV_IOD6INV,
	A2B_GPIODINV_IOD7INV,
	A2B_MBOX0CTL_MB0EN,
	A2B_MBOX0CTL_MB0DIR,
	A2B_MBOX0CTL_MB0EIEN,
	A2B_MBOX0CTL_MB0FIEN,
	A2B_MBOX0CTL_MB0LEN,
	A2B_MBOX0STAT_MB0FULL,
	A2B_MBOX0STAT_MB0EMPTY,
	A2B_MBOX0STAT_MB0FIRQ,
	A2B_MBOX0STAT_MB0EIRQ,
	A2B_MBOX0B0_MBOX0,
	A2B_MBOX0B1_MBOX0,
	A2B_MBOX0B2_MBOX0,
	A2B_MBOX0B3_MBOX0,
	A2B_MBOX1CTL_MB1EN,
	A2B_MBOX1CTL_MB1DIR,
	A2B_MBOX1CTL_MB1EIEN,
	A2B_MBOX1CTL_MB1FIEN,
	A2B_MBOX1CTL_MB1LEN,
	A2B_MBOX1STAT_MB1FULL,
	A2B_MBOX1STAT_MB1EMPTY,
	A2B_MBOX1STAT_MB1FIRQ,
	A2B_MBOX1STAT_MB1EIRQ,
	A2B_MBOX1B0_MBOX1,
	A2B_MBOX1B1_MBOX1,
	A2B_MBOX1B2_MBOX1,
	A2B_MBOX1B3_MBOX1,
	A2B_REGFIELD_MAX,
};
#endif

#define A2B_CHIP_CHIPADR_MASK GENMASK(6, 0)
#define A2B_NODEADR_NODE_MASK GENMASK(3, 0)
#define A2B_NODEADR_PERI_MASK GENMASK(5, 5)
#define A2B_NODEADR_BRCST_MASK GENMASK(7, 7)
#define A2B_VENDOR_VENDOR_MASK GENMASK(7, 0)
#define A2B_PRODUCT_PRODUCT_MASK GENMASK(7, 0)
#define A2B_VERSION_VERSION_MASK GENMASK(7, 0)
#define A2B_CAPABILITY_I2CAVAIL_MASK GENMASK(0, 0)
#define A2B_SWCTL_ENSW_MASK GENMASK(0, 0)
#define A2B_SWCTL_DIAGMODE_MASK GENMASK(3, 3)
#define A2B_SWCTL_MODE_MASK GENMASK(5, 4)
#define A2B_SWCTL_DISNXT_MASK GENMASK(6, 6)
#define A2B_BCDNSLOTS_BCDNSLOTS_MASK GENMASK(5, 0)
#define A2B_LDNSLOTS_LDNSLOTS_MASK GENMASK(5, 0)
#define A2B_LDNSLOTS_DNMASKEN_MASK GENMASK(7, 7)
#define A2B_LUPSLOTS_LUPSLOTS_MASK GENMASK(5, 0)
#define A2B_DNSLOTS_DNSLOTS_MASK GENMASK(5, 0)
#define A2B_UPSLOTS_UPSLOTS_MASK GENMASK(5, 0)
#define A2B_RESPCYCS_RESPCYCS_MASK GENMASK(7, 0)
#define A2B_SLOTFMT_DNSIZE_MASK GENMASK(2, 0)
#define A2B_SLOTFMT_DNFP_MASK GENMASK(3, 3)
#define A2B_SLOTFMT_UPSIZE_MASK GENMASK(6, 4)
#define A2B_SLOTFMT_UPFMT_MASK GENMASK(7, 7)
#define A2B_DATCTL_DNS_MASK GENMASK(0, 0)
#define A2B_DATCTL_UPS_MASK GENMASK(1, 1)
#define A2B_DATCTL_ENDSNIFF_MASK GENMASK(5, 5)
#define A2B_DATCTL_STANDBY_MASK GENMASK(7, 7)
#define A2B_CONTROL_NEWSTRCT_MASK GENMASK(0, 0)
#define A2B_CONTROL_ENDDSC_MASK GENMASK(1, 1)
#define A2B_CONTROL_SOFTRST_MASK GENMASK(2, 2)
#define A2B_CONTROL_SWBYP_MASK GENMASK(3, 3)
#define A2B_CONTROL_XCVRBINV_MASK GENMASK(4, 4)
#define A2B_CONTROL_MSTR_MASK GENMASK(7, 7)
#define A2B_DISCVRY_DRESPCYC_MASK GENMASK(7, 0)
#define A2B_SWSTAT_FIN_MASK GENMASK(0, 0)
#define A2B_SWSTAT_FAULT_MASK GENMASK(1, 1)
#define A2B_SWSTAT_FAULT_CODE_MASK GENMASK(6, 4)
#define A2B_SWSTAT_FAULT_NLOC_MASK GENMASK(7, 7)
#define A2B_INTSTAT_IRQ_MASK GENMASK(0, 0)
#define A2B_INTSRC_INODE_MASK GENMASK(3, 0)
#define A2B_INTSRC_SLVINT_MASK GENMASK(6, 6)
#define A2B_INTSRC_MSTINT_MASK GENMASK(7, 7)
#define A2B_INTTYPE_TYPE_MASK GENMASK(7, 0)
#define A2B_INTPND0_HDCNTERR_MASK GENMASK(0, 0)
#define A2B_INTPND0_DDERR_MASK GENMASK(1, 1)
#define A2B_INTPND0_CRCERR_MASK GENMASK(2, 2)
#define A2B_INTPND0_DPERR_MASK GENMASK(3, 3)
#define A2B_INTPND0_PWRERR_MASK GENMASK(4, 4)
#define A2B_INTPND0_BECOVF_MASK GENMASK(5, 5)
#define A2B_INTPND0_SRFERR_MASK GENMASK(6, 6)
#define A2B_INTPND0_SRFCRCERR_MASK GENMASK(7, 7)
#define A2B_INTPND1_IO0PND_MASK GENMASK(0, 0)
#define A2B_INTPND1_IO1PND_MASK GENMASK(1, 1)
#define A2B_INTPND1_IO2PND_MASK GENMASK(2, 2)
#define A2B_INTPND1_IO3PND_MASK GENMASK(3, 3)
#define A2B_INTPND1_IO4PND_MASK GENMASK(4, 4)
#define A2B_INTPND1_IO5PND_MASK GENMASK(5, 5)
#define A2B_INTPND1_IO6PND_MASK GENMASK(6, 6)
#define A2B_INTPND1_IO7PND_MASK GENMASK(7, 7)
#define A2B_INTPND2_DSCDONE_MASK GENMASK(0, 0)
#define A2B_INTPND2_I2CERR_MASK GENMASK(1, 1)
#define A2B_INTPND2_ICRCERR_MASK GENMASK(2, 2)
#define A2B_INTPND2_SLVIRQ_MASK GENMASK(3, 3)
#define A2B_INTMSK0_HDEIEN_MASK GENMASK(0, 0)
#define A2B_INTMSK0_DDEIEN_MASK GENMASK(1, 1)
#define A2B_INTMSK0_CRCEIEN_MASK GENMASK(2, 2)
#define A2B_INTMSK0_DPEIEN_MASK GENMASK(3, 3)
#define A2B_INTMSK0_PWREIEN_MASK GENMASK(4, 4)
#define A2B_INTMSK0_BECIEN_MASK GENMASK(5, 5)
#define A2B_INTMSK0_SRFEIEN_MASK GENMASK(6, 6)
#define A2B_INTMSK0_SRFCRCEIEN_MASK GENMASK(7, 7)
#define A2B_INTMSK1_IO0IRQEN_MASK GENMASK(0, 0)
#define A2B_INTMSK1_IO1IRQEN_MASK GENMASK(1, 1)
#define A2B_INTMSK1_IO2IRQEN_MASK GENMASK(2, 2)
#define A2B_INTMSK1_IO3IRQEN_MASK GENMASK(3, 3)
#define A2B_INTMSK1_IO4IRQEN_MASK GENMASK(4, 4)
#define A2B_INTMSK1_IO5IRQEN_MASK GENMASK(5, 5)
#define A2B_INTMSK1_IO6IRQEN_MASK GENMASK(6, 6)
#define A2B_INTMSK1_IO7IRQEN_MASK GENMASK(7, 7)
#define A2B_INTMSK2_DSCDIEN_MASK GENMASK(0, 0)
#define A2B_INTMSK2_I2CEIEN_MASK GENMASK(1, 1)
#define A2B_INTMSK2_ICRCEIEN_MASK GENMASK(2, 2)
#define A2B_INTMSK2_SLVIRQEN_MASK GENMASK(3, 3)
#define A2B_BECCTL_ENHDCNT_MASK GENMASK(0, 0)
#define A2B_BECCTL_ENDD_MASK GENMASK(1, 1)
#define A2B_BECCTL_ENCRC_MASK GENMASK(2, 2)
#define A2B_BECCTL_ENDP_MASK GENMASK(3, 3)
#define A2B_BECCTL_ENICRC_MASK GENMASK(4, 4)
#define A2B_BECCTL_THRESHLD_MASK GENMASK(7, 5)
#define A2B_BECNT_BECNT_MASK GENMASK(7, 0)
#define A2B_TESTMODE_PRBSUP_MASK GENMASK(0, 0)
#define A2B_TESTMODE_PRBSDN_MASK GENMASK(1, 1)
#define A2B_TESTMODE_PRBSN2N_MASK GENMASK(2, 2)
#define A2B_TESTMODE_RXDPTH_MASK GENMASK(5, 4)
#define A2B_ERRCNT0_ERRCNT_MASK GENMASK(7, 0)
#define A2B_ERRCNT1_ERRCNT_MASK GENMASK(7, 0)
#define A2B_ERRCNT2_ERRCNT_MASK GENMASK(7, 0)
#define A2B_ERRCNT3_ERRCNT_MASK GENMASK(7, 0)
#define A2B_NODE_NUMBER_MASK GENMASK(3, 0)
#define A2B_NODE_DISCVD_MASK GENMASK(5, 5)
#define A2B_NODE_NLAST_MASK GENMASK(6, 6)
#define A2B_NODE_LAST_MASK GENMASK(7, 7)
#define A2B_DISCSTAT_DNODE_MASK GENMASK(3, 0)
#define A2B_DISCSTAT_DSCACT_MASK GENMASK(7, 7)
#define A2B_TXACTL_TXALEVEL_MASK GENMASK(1, 0)
#define A2B_TXACTL_TXAOVREN_MASK GENMASK(7, 7)
#define A2B_TXBCTL_TXBLEVEL_MASK GENMASK(1, 0)
#define A2B_TXBCTL_TXBOVREN_MASK GENMASK(7, 7)
#define A2B_LINTTYPE_LTYPE_MASK GENMASK(7, 0)
#define A2B_I2CCFG_DATARATE_MASK GENMASK(0, 0)
#define A2B_I2CCFG_EACK_MASK GENMASK(1, 1)
#define A2B_I2CCFG_FRAMERATE_MASK GENMASK(2, 2)
#define A2B_PLLCTL_SSFREQ_MASK GENMASK(1, 0)
#define A2B_PLLCTL_SSDEPTH_MASK GENMASK(3, 3)
#define A2B_PLLCTL_SSMODE_MASK GENMASK(7, 6)
#define A2B_I2SGCFG_TDMMODE_MASK GENMASK(2, 0)
#define A2B_I2SGCFG_RXONDTX1_MASK GENMASK(3, 3)
#define A2B_I2SGCFG_TDMSS_MASK GENMASK(4, 4)
#define A2B_I2SGCFG_ALT_MASK GENMASK(5, 5)
#define A2B_I2SGCFG_EARLY_MASK GENMASK(6, 6)
#define A2B_I2SGCFG_INV_MASK GENMASK(7, 7)
#define A2B_I2SCFG_TX0EN_MASK GENMASK(0, 0)
#define A2B_I2SCFG_TX1EN_MASK GENMASK(1, 1)
#define A2B_I2SCFG_TX2PINTL_MASK GENMASK(2, 2)
#define A2B_I2SCFG_TXBCLKINV_MASK GENMASK(3, 3)
#define A2B_I2SCFG_RX0EN_MASK GENMASK(4, 4)
#define A2B_I2SCFG_RX1EN_MASK GENMASK(5, 5)
#define A2B_I2SCFG_RX2PINTL_MASK GENMASK(6, 6)
#define A2B_I2SCFG_RXBCLKINV_MASK GENMASK(7, 7)
#define A2B_I2SRATE_I2SRATE_MASK GENMASK(2, 0)
#define A2B_I2SRATE_BCLKRATE_MASK GENMASK(5, 3)
#define A2B_I2SRATE_FRAMES_MASK GENMASK(5, 4)
#define A2B_I2SRATE_REDUCE_MASK GENMASK(6, 6)
#define A2B_I2SRATE_SHARE_MASK GENMASK(7, 7)
#define A2B_I2STXOFFSET_TXOFFSET_MASK GENMASK(5, 0)
#define A2B_I2STXOFFSET_TSAFTER_MASK GENMASK(6, 6)
#define A2B_I2STXOFFSET_TSBEFORE_MASK GENMASK(7, 7)
#define A2B_I2SRXOFFSET_RXOFFSET_MASK GENMASK(5, 0)
#define A2B_SYNCOFFSET_SYNCOFFSET_MASK GENMASK(7, 0)
#define A2B_PDMCTL_PDM0EN_MASK GENMASK(0, 0)
#define A2B_PDMCTL_PDM0SLOTS_MASK GENMASK(1, 1)
#define A2B_PDMCTL_PDM1EN_MASK GENMASK(2, 2)
#define A2B_PDMCTL_PDM1SLOTS_MASK GENMASK(3, 3)
#define A2B_PDMCTL_HPFEN_MASK GENMASK(4, 4)
#define A2B_PDMCTL_PDMRATE_MASK GENMASK(6, 5)
#define A2B_ERRMGMT_ERRLSB_MASK GENMASK(0, 0)
#define A2B_ERRMGMT_ERRSIG_MASK GENMASK(1, 1)
#define A2B_ERRMGMT_ERRSLOT_MASK GENMASK(2, 2)
#define A2B_GPIODAT_IO0DAT_MASK GENMASK(0, 0)
#define A2B_GPIODAT_IO1DAT_MASK GENMASK(1, 1)
#define A2B_GPIODAT_IO2DAT_MASK GENMASK(2, 2)
#define A2B_GPIODAT_IO3DAT_MASK GENMASK(3, 3)
#define A2B_GPIODAT_IO4DAT_MASK GENMASK(4, 4)
#define A2B_GPIODAT_IO5DAT_MASK GENMASK(5, 5)
#define A2B_GPIODAT_IO6DAT_MASK GENMASK(6, 6)
#define A2B_GPIODAT_IO7DAT_MASK GENMASK(7, 7)
#define A2B_GPIODATSET_IO0DSET_MASK GENMASK(0, 0)
#define A2B_GPIODATSET_IO1DSET_MASK GENMASK(1, 1)
#define A2B_GPIODATSET_IO2DSET_MASK GENMASK(2, 2)
#define A2B_GPIODATSET_IO3DSET_MASK GENMASK(3, 3)
#define A2B_GPIODATSET_IO4DSET_MASK GENMASK(4, 4)
#define A2B_GPIODATSET_IO5DSET_MASK GENMASK(5, 5)
#define A2B_GPIODATSET_IO6DSET_MASK GENMASK(6, 6)
#define A2B_GPIODATSET_IO7DSET_MASK GENMASK(7, 7)
#define A2B_GPIODATCLR_IO0DCLR_MASK GENMASK(0, 0)
#define A2B_GPIODATCLR_IO1DCLR_MASK GENMASK(1, 1)
#define A2B_GPIODATCLR_IO2DCLR_MASK GENMASK(2, 2)
#define A2B_GPIODATCLR_IO3DCLR_MASK GENMASK(3, 3)
#define A2B_GPIODATCLR_IO4DCLR_MASK GENMASK(4, 4)
#define A2B_GPIODATCLR_IO5DCLR_MASK GENMASK(5, 5)
#define A2B_GPIODATCLR_IO6DCLR_MASK GENMASK(6, 6)
#define A2B_GPIODATCLR_IO7DCLR_MASK GENMASK(7, 7)
#define A2B_GPIOOEN_IO0OEN_MASK GENMASK(0, 0)
#define A2B_GPIOOEN_IO1OEN_MASK GENMASK(1, 1)
#define A2B_GPIOOEN_IO2OEN_MASK GENMASK(2, 2)
#define A2B_GPIOOEN_IO3OEN_MASK GENMASK(3, 3)
#define A2B_GPIOOEN_IO4OEN_MASK GENMASK(4, 4)
#define A2B_GPIOOEN_IO5OEN_MASK GENMASK(5, 5)
#define A2B_GPIOOEN_IO6OEN_MASK GENMASK(6, 6)
#define A2B_GPIOOEN_IO7OEN_MASK GENMASK(7, 7)
#define A2B_GPIOIEN_IO0IEN_MASK GENMASK(0, 0)
#define A2B_GPIOIEN_IO1IEN_MASK GENMASK(1, 1)
#define A2B_GPIOIEN_IO2IEN_MASK GENMASK(2, 2)
#define A2B_GPIOIEN_IO3IEN_MASK GENMASK(3, 3)
#define A2B_GPIOIEN_IO4IEN_MASK GENMASK(4, 4)
#define A2B_GPIOIEN_IO5IEN_MASK GENMASK(5, 5)
#define A2B_GPIOIEN_IO6IEN_MASK GENMASK(6, 6)
#define A2B_GPIOIEN_IO7IEN_MASK GENMASK(7, 7)
#define A2B_GPIOIN_IO0IN_MASK GENMASK(0, 0)
#define A2B_GPIOIN_IO1IN_MASK GENMASK(1, 1)
#define A2B_GPIOIN_IO2IN_MASK GENMASK(2, 2)
#define A2B_GPIOIN_IO3IN_MASK GENMASK(3, 3)
#define A2B_GPIOIN_IO4IN_MASK GENMASK(4, 4)
#define A2B_GPIOIN_IO5IN_MASK GENMASK(5, 5)
#define A2B_GPIOIN_IO6IN_MASK GENMASK(6, 6)
#define A2B_GPIOIN_IO7IN_MASK GENMASK(7, 7)
#define A2B_PINTEN_IO0IE_MASK GENMASK(0, 0)
#define A2B_PINTEN_IO1IE_MASK GENMASK(1, 1)
#define A2B_PINTEN_IO2IE_MASK GENMASK(2, 2)
#define A2B_PINTEN_IO3IE_MASK GENMASK(3, 3)
#define A2B_PINTEN_IO4IE_MASK GENMASK(4, 4)
#define A2B_PINTEN_IO5IE_MASK GENMASK(5, 5)
#define A2B_PINTEN_IO6IE_MASK GENMASK(6, 6)
#define A2B_PINTEN_IO7IE_MASK GENMASK(7, 7)
#define A2B_PINTINV_IO0INV_MASK GENMASK(0, 0)
#define A2B_PINTINV_IO1INV_MASK GENMASK(1, 1)
#define A2B_PINTINV_IO2INV_MASK GENMASK(2, 2)
#define A2B_PINTINV_IO3INV_MASK GENMASK(3, 3)
#define A2B_PINTINV_IO4INV_MASK GENMASK(4, 4)
#define A2B_PINTINV_IO5INV_MASK GENMASK(5, 5)
#define A2B_PINTINV_IO6INV_MASK GENMASK(6, 6)
#define A2B_PINTINV_IO7INV_MASK GENMASK(7, 7)
#define A2B_PINCFG_DRVSTR_MASK GENMASK(0, 0)
#define A2B_PINCFG_IRQINV_MASK GENMASK(4, 4)
#define A2B_PINCFG_IRQTS_MASK GENMASK(5, 5)
#define A2B_I2STEST_PATTRN2TX_MASK GENMASK(0, 0)
#define A2B_I2STEST_LOOPBK2TX_MASK GENMASK(1, 1)
#define A2B_I2STEST_RX2LOOPBK_MASK GENMASK(2, 2)
#define A2B_I2STEST_SELRX1_MASK GENMASK(3, 3)
#define A2B_I2STEST_BUSLOOPBK_MASK GENMASK(4, 4)
#define A2B_RAISE_RAISE_MASK GENMASK(7, 0)
#define A2B_GENERR_GENHCERR_MASK GENMASK(0, 0)
#define A2B_GENERR_GENDDERR_MASK GENMASK(1, 1)
#define A2B_GENERR_GENCRCERR_MASK GENMASK(2, 2)
#define A2B_GENERR_GENDPERR_MASK GENMASK(3, 3)
#define A2B_GENERR_GENICRCERR_MASK GENMASK(4, 4)
#define A2B_I2SRRATE_RRDIV_MASK GENMASK(5, 0)
#define A2B_I2SRRATE_RBUS_MASK GENMASK(7, 7)
#define A2B_I2SRRCTL_ENVLSB_MASK GENMASK(0, 0)
#define A2B_I2SRRCTL_ENXBIT_MASK GENMASK(1, 1)
#define A2B_I2SRRCTL_ENSTRB_MASK GENMASK(4, 4)
#define A2B_I2SRRCTL_STRBDIR_MASK GENMASK(5, 5)
#define A2B_I2SRRSOFFS_RRSOFFSET_MASK GENMASK(1, 0)
#define A2B_CLK1CFG_CLK1DIV_MASK GENMASK(3, 0)
#define A2B_CLK1CFG_CLK1PDIV_MASK GENMASK(5, 5)
#define A2B_CLK1CFG_CLK1INV_MASK GENMASK(6, 6)
#define A2B_CLK1CFG_CLK1EN_MASK GENMASK(7, 7)
#define A2B_CLK2CFG_CLK1DIV_MASK GENMASK(3, 0)
#define A2B_CLK2CFG_CLK1PDIV_MASK GENMASK(5, 5)
#define A2B_CLK2CFG_CLK1INV_MASK GENMASK(6, 6)
#define A2B_CLK2CFG_CLK1EN_MASK GENMASK(7, 7)
#define A2B_BMMCFG_BMMEN_MASK GENMASK(0, 0)
#define A2B_BMMCFG_BMMRXEN_MASK GENMASK(1, 1)
#define A2B_BMMCFG_BMMNDSC_MASK GENMASK(2, 2)
#define A2B_SUSCFG_SUSSEL_MASK GENMASK(2, 0)
#define A2B_SUSCFG_SUSOE_MASK GENMASK(4, 4)
#define A2B_SUSCFG_SUSDIS_MASK GENMASK(5, 5)
#define A2B_PDMCTL2_PDMDEST_MASK GENMASK(1, 0)
#define A2B_PDMCTL2_PDM0FFRST_MASK GENMASK(2, 2)
#define A2B_PDMCTL2_PDM1FFRST_MASK GENMASK(3, 3)
#define A2B_PDMCTL2_PDMALTCLK_MASK GENMASK(4, 4)
#define A2B_PDMCTL2_PDMINVCLK_MASK GENMASK(5, 5)
#define A2B_UPMASK0_RXUPSLOT00_MASK GENMASK(0, 0)
#define A2B_UPMASK0_RXUPSLOT01_MASK GENMASK(1, 1)
#define A2B_UPMASK0_RXUPSLOT02_MASK GENMASK(2, 2)
#define A2B_UPMASK0_RXUPSLOT03_MASK GENMASK(3, 3)
#define A2B_UPMASK0_RXUPSLOT04_MASK GENMASK(4, 4)
#define A2B_UPMASK0_RXUPSLOT05_MASK GENMASK(5, 5)
#define A2B_UPMASK0_RXUPSLOT06_MASK GENMASK(6, 6)
#define A2B_UPMASK0_RXUPSLOT07_MASK GENMASK(7, 7)
#define A2B_UPMASK1_RXUPSLOT08_MASK GENMASK(0, 0)
#define A2B_UPMASK1_RXUPSLOT09_MASK GENMASK(1, 1)
#define A2B_UPMASK1_RXUPSLOT10_MASK GENMASK(2, 2)
#define A2B_UPMASK1_RXUPSLOT11_MASK GENMASK(3, 3)
#define A2B_UPMASK1_RXUPSLOT12_MASK GENMASK(4, 4)
#define A2B_UPMASK1_RXUPSLOT13_MASK GENMASK(5, 5)
#define A2B_UPMASK1_RXUPSLOT14_MASK GENMASK(6, 6)
#define A2B_UPMASK1_RXUPSLOT15_MASK GENMASK(7, 7)
#define A2B_UPMASK2_RXUPSLOT16_MASK GENMASK(0, 0)
#define A2B_UPMASK2_RXUPSLOT17_MASK GENMASK(1, 1)
#define A2B_UPMASK2_RXUPSLOT18_MASK GENMASK(2, 2)
#define A2B_UPMASK2_RXUPSLOT19_MASK GENMASK(3, 3)
#define A2B_UPMASK2_RXUPSLOT20_MASK GENMASK(4, 4)
#define A2B_UPMASK2_RXUPSLOT21_MASK GENMASK(5, 5)
#define A2B_UPMASK2_RXUPSLOT22_MASK GENMASK(6, 6)
#define A2B_UPMASK2_RXUPSLOT23_MASK GENMASK(7, 7)
#define A2B_UPMASK3_RXUPSLOT24_MASK GENMASK(0, 0)
#define A2B_UPMASK3_RXUPSLOT25_MASK GENMASK(1, 1)
#define A2B_UPMASK3_RXUPSLOT26_MASK GENMASK(2, 2)
#define A2B_UPMASK3_RXUPSLOT27_MASK GENMASK(3, 3)
#define A2B_UPMASK3_RXUPSLOT28_MASK GENMASK(4, 4)
#define A2B_UPMASK3_RXUPSLOT29_MASK GENMASK(5, 5)
#define A2B_UPMASK3_RXUPSLOT30_MASK GENMASK(6, 6)
#define A2B_UPMASK3_RXUPSLOT31_MASK GENMASK(7, 7)
#define A2B_UPOFFSET_UPOFFSET_MASK GENMASK(4, 0)
#define A2B_DNMASK0_RXDNSLOT00_MASK GENMASK(0, 0)
#define A2B_DNMASK0_RXDNSLOT01_MASK GENMASK(1, 1)
#define A2B_DNMASK0_RXDNSLOT02_MASK GENMASK(2, 2)
#define A2B_DNMASK0_RXDNSLOT03_MASK GENMASK(3, 3)
#define A2B_DNMASK0_RXDNSLOT04_MASK GENMASK(4, 4)
#define A2B_DNMASK0_RXDNSLOT05_MASK GENMASK(5, 5)
#define A2B_DNMASK0_RXDNSLOT06_MASK GENMASK(6, 6)
#define A2B_DNMASK0_RXDNSLOT07_MASK GENMASK(7, 7)
#define A2B_DNMASK1_RXDNSLOT08_MASK GENMASK(0, 0)
#define A2B_DNMASK1_RXDNSLOT09_MASK GENMASK(1, 1)
#define A2B_DNMASK1_RXDNSLOT10_MASK GENMASK(2, 2)
#define A2B_DNMASK1_RXDNSLOT11_MASK GENMASK(3, 3)
#define A2B_DNMASK1_RXDNSLOT12_MASK GENMASK(4, 4)
#define A2B_DNMASK1_RXDNSLOT13_MASK GENMASK(5, 5)
#define A2B_DNMASK1_RXDNSLOT14_MASK GENMASK(6, 6)
#define A2B_DNMASK1_RXDNSLOT15_MASK GENMASK(7, 7)
#define A2B_DNMASK2_RXDNSLOT16_MASK GENMASK(0, 0)
#define A2B_DNMASK2_RXDNSLOT17_MASK GENMASK(1, 1)
#define A2B_DNMASK2_RXDNSLOT18_MASK GENMASK(2, 2)
#define A2B_DNMASK2_RXDNSLOT19_MASK GENMASK(3, 3)
#define A2B_DNMASK2_RXDNSLOT20_MASK GENMASK(4, 4)
#define A2B_DNMASK2_RXDNSLOT21_MASK GENMASK(5, 5)
#define A2B_DNMASK2_RXDNSLOT22_MASK GENMASK(6, 6)
#define A2B_DNMASK2_RXDNSLOT23_MASK GENMASK(7, 7)
#define A2B_DNMASK3_RXDNSLOT24_MASK GENMASK(0, 0)
#define A2B_DNMASK3_RXDNSLOT25_MASK GENMASK(1, 1)
#define A2B_DNMASK3_RXDNSLOT26_MASK GENMASK(2, 2)
#define A2B_DNMASK3_RXDNSLOT27_MASK GENMASK(3, 3)
#define A2B_DNMASK3_RXDNSLOT28_MASK GENMASK(4, 4)
#define A2B_DNMASK3_RXDNSLOT29_MASK GENMASK(5, 5)
#define A2B_DNMASK3_RXDNSLOT30_MASK GENMASK(6, 6)
#define A2B_DNMASK3_RXDNSLOT31_MASK GENMASK(7, 7)
#define A2B_DNOFFSET_DNOFFSET_MASK GENMASK(4, 0)
#define A2B_CHIPID0_CHIPID_MASK GENMASK(7, 0)
#define A2B_CHIPID1_CHIPID_MASK GENMASK(7, 0)
#define A2B_CHIPID2_CHIPID_MASK GENMASK(7, 0)
#define A2B_CHIPID3_CHIPID_MASK GENMASK(7, 0)
#define A2B_CHIPID4_CHIPID_MASK GENMASK(7, 0)
#define A2B_CHIPID5_CHIPID_MASK GENMASK(7, 0)
#define A2B_GPIODEN_IOD0EN_MASK GENMASK(0, 0)
#define A2B_GPIODEN_IOD1EN_MASK GENMASK(1, 1)
#define A2B_GPIODEN_IOD2EN_MASK GENMASK(2, 2)
#define A2B_GPIODEN_IOD3EN_MASK GENMASK(3, 3)
#define A2B_GPIODEN_IOD4EN_MASK GENMASK(4, 4)
#define A2B_GPIODEN_IOD5EN_MASK GENMASK(5, 5)
#define A2B_GPIODEN_IOD6EN_MASK GENMASK(6, 6)
#define A2B_GPIODEN_IOD7EN_MASK GENMASK(7, 7)
#define A2B_GPIOD0MSK_IOD0MSK_MASK GENMASK(7, 0)
#define A2B_GPIOD1MSK_IOD1MSK_MASK GENMASK(7, 0)
#define A2B_GPIOD2MSK_IOD2MSK_MASK GENMASK(7, 0)
#define A2B_GPIOD3MSK_IOD3MSK_MASK GENMASK(7, 0)
#define A2B_GPIOD4MSK_IOD4MSK_MASK GENMASK(7, 0)
#define A2B_GPIOD5MSK_IOD5MSK_MASK GENMASK(7, 0)
#define A2B_GPIOD6MSK_IOD6MSK_MASK GENMASK(7, 0)
#define A2B_GPIOD7MSK_IOD7MSK_MASK GENMASK(7, 0)
#define A2B_GPIODDAT_IOD0DAT_MASK GENMASK(0, 0)
#define A2B_GPIODDAT_IOD1DAT_MASK GENMASK(1, 1)
#define A2B_GPIODDAT_IOD2DAT_MASK GENMASK(2, 2)
#define A2B_GPIODDAT_IOD3DAT_MASK GENMASK(3, 3)
#define A2B_GPIODDAT_IOD4DAT_MASK GENMASK(4, 4)
#define A2B_GPIODDAT_IOD5DAT_MASK GENMASK(5, 5)
#define A2B_GPIODDAT_IOD6DAT_MASK GENMASK(6, 6)
#define A2B_GPIODDAT_IOD7DAT_MASK GENMASK(7, 7)
#define A2B_GPIODINV_IOD0INV_MASK GENMASK(0, 0)
#define A2B_GPIODINV_IOD1INV_MASK GENMASK(1, 1)
#define A2B_GPIODINV_IOD2INV_MASK GENMASK(2, 2)
#define A2B_GPIODINV_IOD3INV_MASK GENMASK(3, 3)
#define A2B_GPIODINV_IOD4INV_MASK GENMASK(4, 4)
#define A2B_GPIODINV_IOD5INV_MASK GENMASK(5, 5)
#define A2B_GPIODINV_IOD6INV_MASK GENMASK(6, 6)
#define A2B_GPIODINV_IOD7INV_MASK GENMASK(7, 7)
#define A2B_MBOX0CTL_MB0EN_MASK GENMASK(0, 0)
#define A2B_MBOX0CTL_MB0DIR_MASK GENMASK(1, 1)
#define A2B_MBOX0CTL_MB0EIEN_MASK GENMASK(2, 2)
#define A2B_MBOX0CTL_MB0FIEN_MASK GENMASK(3, 3)
#define A2B_MBOX0CTL_MB0LEN_MASK GENMASK(5, 4)
#define A2B_MBOX0STAT_MB0FULL_MASK GENMASK(0, 0)
#define A2B_MBOX0STAT_MB0EMPTY_MASK GENMASK(1, 1)
#define A2B_MBOX0STAT_MB0FIRQ_MASK GENMASK(4, 4)
#define A2B_MBOX0STAT_MB0EIRQ_MASK GENMASK(5, 5)
#define A2B_MBOX0B0_MBOX0_MASK GENMASK(7, 0)
#define A2B_MBOX0B1_MBOX0_MASK GENMASK(7, 0)
#define A2B_MBOX0B2_MBOX0_MASK GENMASK(7, 0)
#define A2B_MBOX0B3_MBOX0_MASK GENMASK(7, 0)
#define A2B_MBOX1CTL_MB1EN_MASK GENMASK(0, 0)
#define A2B_MBOX1CTL_MB1DIR_MASK GENMASK(1, 1)
#define A2B_MBOX1CTL_MB1EIEN_MASK GENMASK(2, 2)
#define A2B_MBOX1CTL_MB1FIEN_MASK GENMASK(3, 3)
#define A2B_MBOX1CTL_MB1LEN_MASK GENMASK(5, 4)
#define A2B_MBOX1STAT_MB1FULL_MASK GENMASK(0, 0)
#define A2B_MBOX1STAT_MB1EMPTY_MASK GENMASK(1, 1)
#define A2B_MBOX1STAT_MB1FIRQ_MASK GENMASK(4, 4)
#define A2B_MBOX1STAT_MB1EIRQ_MASK GENMASK(5, 5)
#define A2B_MBOX1B0_MBOX1_MASK GENMASK(7, 0)
#define A2B_MBOX1B1_MBOX1_MASK GENMASK(7, 0)
#define A2B_MBOX1B2_MBOX1_MASK GENMASK(7, 0)
#define A2B_MBOX1B3_MBOX1_MASK GENMASK(7, 0)

#endif /* _AD24XX_H */
