# SPDX-License-Identifier: GPL-2.0-only
snd-soc-adi-axi-i2s-y := axi-i2s.o
snd-soc-adi-axi-spdif-y := axi-spdif.o
snd-soc-a2b-audio-graph-card2-y := a2b-audio-graph-card2.o

obj-$(CONFIG_SND_SOC_ADI_AXI_I2S) += snd-soc-adi-axi-i2s.o
obj-$(CONFIG_SND_SOC_ADI_AXI_SPDIF) += snd-soc-adi-axi-spdif.o
obj-$(CONFIG_SND_SOC_A2B_AUDIO_GRAPH_CARD2) += snd-soc-a2b-audio-graph-card2.o
