# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_A2B) += a2b.o
obj-$(CONFIG_A2B_AD24XX) += ad24xx-i2c.o
obj-$(CONFIG_A2B_AD24XX) += ad24xx-node.o
obj-$(CONFIG_A2B_AD24XX) += ad24xx-gpio.o
obj-$(CONFIG_A2B_AD24XX) += ad24xx-codec.o
obj-$(CONFIG_A2B_AD24XX) += i2c-ad24xx.o
